extends Node

var FAMILY_SANDSTONE = [FLOOR_SANDSTONE, WALL_SANDSTONE]
var FAMILY_BRICK_DARK = [FLOOR_BRICK_DARK, WALL_BRICK_DARK]

const WALL_SANDSTONE = [0,9]
const WALL_BRICK_DARK = [20,26]

const FLOOR_SANDSTONE = [10,19]
const FLOOR_BRICK_DARK = [27,33]